export const possibleItems = [
  "bacon",
  "baking powder",
  "baking soda",
  "basil",
  "black pepper",
  "breadcrumbs",
  "butter",
  "chicken",
  "chicken breast",
  "chickpeas",
  "chilli flakes",
  "chilli powder",
  "cilantro",
  "cornstarch",
  "cumin",
  "eggplants",
  "eggs",
  "fettuccine pasta",
  "flour",
  "garlic",
  "garlic powder",
  "green onions",
  "green peppercorns",
  "half & half",
  "jasmine rice",
  "ketchup",
  "kosher salt",
  "lemon zest",
  "marinara sauce",
  "milk",
  "mozzarella cheese",
  "oil",
  "olive oil",
  "onions",
  "paprika",
  "parmesan cheese",
  "parsley",
  "pink peppercorns",
  "pork",
  "red bell pepper",
  "salt",
  "scallops",
  "soy sauce",
  "spaghetti pasta",
  "sugar",
  "tenderloin roast",
  "tomato paste",
  "tomatoes",
  "vinegar",
  "white mushrooms",
];
